# Configuration for probot-stale - https://github.com/probot/stale

daysUntilStale: 31
daysUntilClose: 7

staleLabel: stale

markComment: false
closeComment: >
  Sorry, this PR looks like it's fallen behind the curve! As a result,
  it's being closed to help keep the PR list clean. Please feel free to
  re-open if you are still interested in merging these changes - and
  either way, thank you for your contributions!

only: pulls
