version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/xiva-client
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: run-build
          command: yarn build
      - run:
          name: Upload build
          command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/* $SSH_USER@$SSH_HOST:xivanalysis/client/deploy-cache
      - run:
          name: Run deploy script
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd xivanalysis/client && ./deploy.sh $CIRCLE_SHA1"
